lexik_jwt_authentication:
    private_key_path: '%kernel.project_dir%/config/jwt/private_decrypted.pem'
    secret_key: '%kernel.project_dir%/config/jwt/private.pem'
    public_key: '%kernel.project_dir%/config/jwt/public.pem'
    token_ttl: 3600 
