security:
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: "auto"

  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    register:
      pattern: ^/api/register
      security: false

    login:
      pattern: ^/api/login
      security: false

    api:
      pattern: ^/api
      stateless: true
      provider: app_user_provider
      jwt: ~

    main:
      lazy: true
      provider: app_user_provider
      logout: true

  access_control:
    - { path: ^/api/admin, roles: ROLE_ADMIN }
    - { path: ^/api/manager, roles: ROLE_MANAGER }
    - { path: ^/api/client, roles: ROLE_CLIENT }
    - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }

when@test:
  security:
    password_hashers:
      Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
        algorithm: auto
        cost: 4
        time_cost: 3
        memory_cost: 10
